---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: talhelper
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/budimanjojo/talhelper/v3/cmd.version={{.Version}}
  - id: talhelper-windows-amd64
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/budimanjojo/talhelper/v3/cmd.version={{.Version}}
archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge pull request #\d+ from'
      - "^docs"
      - "^test"

aurs:
  - name: talhelper-bin
    homepage: "https://github.com/budimanjojo/talhelper"
    description: "A tool to help creating Talos cluster in GitOps way."
    maintainers:
      - Budiman Jojo <budimanjojo at gmail dot com>
    license: "BSD-3-Clause"
    skip_upload: "auto"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/talhelper-bin.git"
    package: |-
      # bin
      install -Dm755 "./{{ .ProjectName }}" "${pkgdir}/usr/bin/{{ .ProjectName }}"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/{{ .ProjectName }}/LICENSE"
      # completions
      "${pkgdir}/usr/bin/{{ .ProjectName }}" completion bash | install -Dm644 /dev/stdin "${pkgdir}/usr/share/bash-completion/completions/{{ .ProjectName }}"
      "${pkgdir}/usr/bin/{{ .ProjectName }}" completion fish | install -Dm644 /dev/stdin "${pkgdir}/usr/share/fish/completions/{{ .ProjectName }}.fish"
      "${pkgdir}/usr/bin/{{ .ProjectName }}" completion zsh | install -Dm644 /dev/stdin "${pkgdir}/usr/share/zsh/site-functions/_{{ .ProjectName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

scoops:
  - url_template: "https://github.com/budimanjojo/talhelper/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: budimanjojo
      name: talhelper
      branch: master
      pull_request:
        enabled: false
    commit_msg_template: "feat: update Scoop for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/budimanjojo/talhelper"
    description: "A tool to help creating Talos kubernetes cluster"
    license: BSD-3
    depends:
      - sops

dockers:
  - image_templates:
      - "ghcr.io/budimanjojo/{{.ProjectName}}:v{{.Version}}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/budimanjojo/{{.ProjectName}}"
      - "--label=org.opencontainers.image.source=https://github.com/budimanjojo/{{.ProjectName}}"
      - "--label=org.opencontainers.image.licenses=BSD-3-Clause"
      - "--label=org.opencontainers.image.authors=Budiman Jojo <budimanjojo@gmail.com>"
      - "--label=org.opencontainers.image.description=A tool to help creating Talos kubernetes cluster"
  - image_templates:
      - "ghcr.io/budimanjojo/{{.ProjectName}}:v{{.Version}}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/budimanjojo/{{.ProjectName}}"
      - "--label=org.opencontainers.image.source=https://github.com/budimanjojo/{{.ProjectName}}"
      - "--label=org.opencontainers.image.licenses=BSD-3-Clause"
      - "--label=org.opencontainers.image.authors=Budiman Jojo <budimanjojo@gmail.com>"
      - "--label=org.opencontainers.image.description=A tool to help creating Talos kubernetes cluster"

docker_manifests:
  - name_template: "ghcr.io/budimanjojo/{{.ProjectName}}:v{{.Version}}"
    image_templates:
      - "ghcr.io/budimanjojo/{{.ProjectName}}:v{{.Version}}-amd64"
      - "ghcr.io/budimanjojo/{{.ProjectName}}:v{{.Version}}-arm64v8"
  - name_template: "ghcr.io/budimanjojo/{{.ProjectName}}:latest"
    image_templates:
      - "ghcr.io/budimanjojo/{{.ProjectName}}:v{{.Version}}-amd64"
      - "ghcr.io/budimanjojo/{{.ProjectName}}:v{{.Version}}-arm64v8"
