name: Test Nix Build
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master
permissions:
  contents: read
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: cachix/install-nix-action@v31
      - uses: workflow/nix-shell-action@v4.0.0
        with:
          flakes-from-devshell: true
          script: bash ./scripts/nix-build-last-commit.sh
      - run: ./result/bin/talhelper
